# copied code from github action repo, using yml extension yet another markup langauge
# using for all available test spec files

name: Regression End-to-end tests
on:
  # schedule:
  #   - cron: '30 21 * * 1-4' # Mon-Fri 8PM IST
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch: # allows manual run
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install dependencies with caching
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7