# Using for running single test spec file
# using for Slack notification
# Using for Mochawesome report on GitHub Actions
# Slack: first copy available codes from github slack report > create slack account > create channel > channel settings
# > click integration > click on Add a app > install webhooks > use the same variable > go to GitHub > Settings
# Click on Secret and variable > add same variable names as mentioned below

name: Sanity Build
on:
  # schedule:
  #   - cron: '30 21 * * 1-4' # Mon-Fri 8PM IST
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch: # allows manual run
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install dependencies with caching
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          command: npm run test:addToCart

      - name: Cypress Test Report
        if: always() # Ensure this step runs even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report
          path: cypress/reports/html


      - name: Slack Notification
        if: always() # Ensure this step runs even if the previous step fails
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Test Automation Report https://github.com/officialsudhanshugautam/Cypress-E2E-NehaBhasin/actions/runs/${{github.run_id}}'
          SLACK_TITLE: Cypress Web Test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
