name: Sanity Build
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install dependencies with caching
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          command: npm run test:addToCard

      - name: Cypress Test Report
        if: always() # Ensure this step runs even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report
          path: cypress/reports/html

        
